--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/anlocode/mygo _2/al_ip/FIFO_8_32.vhd
 -- Date	:	2025 11 03
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY FIFO_8_32 IS
PORT (
	di	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clkw	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	clkr	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	do	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC
	);
END FIFO_8_32;

ARCHITECTURE struct OF FIFO_8_32 IS

	BEGIN
	fifo_inst : EG_LOGIC_FIFO
		GENERIC MAP (
			DATA_WIDTH_W			=> 8,
			DATA_DEPTH_W			=> 2048,
			DATA_WIDTH_R			=> 32,
			DATA_DEPTH_R			=> 512,
			ENDIAN				=> "BIG",
			RESETMODE			=> "ASYNC",
			REGMODE_R			=> "NOREG",
			E					=> 0,
			F					=> 2048,
			ASYNC_RESET_RELEASE	=> "SYNC"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clkw	=> clkw,
			we	=> we,
			csw	=> "111",
			clkr	=> clkr,
			ore	=> '0',
			re	=> re,
			csr	=> "111",
			do	=> do,
			empty_flag	=> empty_flag,
			aempty_flag	=> OPEN,
			full_flag	=> full_flag,
			afull_flag	=> OPEN
		);

END struct;
